---
galaxy_info:
  role_name: tree
  author: Ted Cook
  description: An Ansible role to install and configure tree
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - tree

dependencies: []
