---
galaxy_info:
  author: Andrew Rothstein
  description: installs the docker-ce
  company: BlackRock Financial Management
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: Alpine
      versions:
        - all
    - name: Archlinux
      versions:
        - all
    - name: Debian
      versions:
        - bullseye
        - buster
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - 34
    - name: Ubuntu
      versions:
        - bionic
        - focal
  galaxy_tags:
    - development
  role_name: docker_engine

dependencies:
  - role: andrewrothstein.tls
    version: v0.1.3
