---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: fedora32
    # See: https://github.com/geerlingguy/ansible-role-ansible/issues/18
    # - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian10

    - MOLECULE_DISTRO: centos8
      MOLECULE_PLAYBOOK: playbook-pip.yml

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
  - cd geerlingguy.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
